export const activeJobs = [
  {
    id: 1,
    name: "Full-stack Engineer",
    experience: 1,
    mode: "Full day",
    city: "London",
    description:
      "The team we are recruiting for is implementing a software framework for developing data products based on Apache Spark technology. This framework is intended to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved. This framework is designed to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved",
    salary: 10000,
    company: "Bemo team",
    logo: "https://cdn.getro.com/companies/2da1be3c-a9cd-5af9-8ec5-e67430ea3196",
    date: "2024-02-10T01:30:00.000-05:00",
  },
  {
    id: 2,
    name: "Junior",
    experience: 1,
    mode: "Full day",
    city: "London",
    description:
      "The team we are recruiting for is implementing a software framework for developing data products based on Apache Spark technology. This framework is intended to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved. This framework is designed to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved",
    salary: 8000,
    company: "Bemo team",
    logo: "https://cdn.getro.com/companies/2da1be3c-a9cd-5af9-8ec5-e67430ea3196",
    date: "2024-02-10T01:30:00.000-05:00",
  },
  {
    id: 3,
    name: "Middle",
    experience: 1,
    mode: "Full day",
    city: "London",
    description:
      "The team we are recruiting for is implementing a software framework for developing data products based on Apache Spark technology. This framework is intended to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved. This framework is designed to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved",
    salary: 11000,
    company: "Bemo team",
    logo: "https://cdn.getro.com/companies/2da1be3c-a9cd-5af9-8ec5-e67430ea3196",
    date: "2024-02-10T01:30:00.000-05:00",
  },
  {
    id: 4,
    name: "Full-stack Engineer",
    experience: 1,
    mode: "Full day",
    city: "London",
    description:
      "The team we are recruiting for is implementing a software framework for developing data products based on Apache Spark technology. This framework is intended to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved. This framework is designed to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved",
    salary: 7000,
    company: "Bemo team",
    logo: "https://cdn.getro.com/companies/2da1be3c-a9cd-5af9-8ec5-e67430ea3196",
    date: "2024-02-10T01:30:00.000-05:00",
  },
  {
    id: 5,
    name: "Junior",
    experience: 1,
    mode: "Full day",
    city: "London",
    description:
      "The team we are recruiting for is implementing a software framework for developing data products based on Apache Spark technology. This framework is intended to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved. This framework is designed to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved",
    salary: 8000,
    company: "Bemo team",
    logo: "https://cdn.getro.com/companies/2da1be3c-a9cd-5af9-8ec5-e67430ea3196",
    date: "2024-02-10T01:30:00.000-05:00",
  },
  {
    id: 6,
    name: "Full-stack Engineer",
    experience: 1,
    mode: "Full day",
    city: "London",
    description:
      "The team we are recruiting for is implementing a software framework for developing data products based on Apache Spark technology. This framework is intended to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved. This framework is designed to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved",
    salary: 10000,
    company: "Bemo team",
    logo: "https://cdn.getro.com/companies/2da1be3c-a9cd-5af9-8ec5-e67430ea3196",
    date: "2024-02-10T01:30:00.000-05:00",
  },
  {
    id: 7,
    name: "Middle",
    experience: 1,
    mode: "Full day",
    city: "London",
    description:
      "The team we are recruiting for is implementing a software framework for developing data products based on Apache Spark technology. This framework is intended to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved. This framework is designed to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved",
    salary: 12000,
    company: "Bemo team",
    logo: "https://cdn.getro.com/companies/2da1be3c-a9cd-5af9-8ec5-e67430ea3196",
    date: "2024-02-10T01:30:00.000-05:00",
  },
  {
    id: 8,
    name: "Full-stack Engineer",
    experience: 1,
    mode: "Full day",
    city: "London",
    description:
      "The team we are recruiting for is implementing a software framework for developing data products based on Apache Spark technology. This framework is intended to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved. This framework is designed to replace the historically established heterogeneous solutions of application teams, thanks to which it will be achieved",
    salary: 10000,
    company: "Bemo team",
    logo: "https://cdn.getro.com/companies/2da1be3c-a9cd-5af9-8ec5-e67430ea3196",
    date: "2024-02-10T01:30:00.000-05:00",
  },
];
